# Generated by Django 2.2.9 on 2020-01-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_auto_20200103_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide', to='beacon.Category'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
