# Generated by Django 2.2.9 on 2020-01-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0004_auto_20200104_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'verbose_name': 'Change Log', 'verbose_name_plural': 'Change Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='chapterrevision',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guiderevision',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sectionrevision',
            unique_together=set(),
        ),
    ]
