# Generated by Django 2.2.9 on 2020-01-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_auto_20200104_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterrevision',
            name='changelog',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='guiderevision',
            name='changelog',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionrevision',
            name='changelog',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
