# Generated by Django 2.2.9 on 2020-01-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_auto_20200109_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='chapterrevision',
            name='slug',
            field=models.SlugField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='guiderevision',
            name='slug',
            field=models.SlugField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='sectionrevision',
            name='slug',
            field=models.SlugField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=500),
        ),
    ]
