# Generated by Django 2.2.9 on 2020-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0008_auto_20200109_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='stage',
            new_name='order',
        ),
        migrations.AddField(
            model_name='introduction',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='introduction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='content',
        ),
    ]
