# Generated by Django 2.2.9 on 2020-01-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0010_auto_20200110_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterrevision',
            name='step',
        ),
        migrations.RemoveField(
            model_name='sectionrevision',
            name='step',
        ),
    ]
