# Generated by Django 2.2.9 on 2020-01-11 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('beacon', '0011_auto_20200111_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255, null=True)),
                ('stage', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explains', to='beacon.Chapter')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explains', to='person.Person')),
            ],
            options={
                'verbose_name': 'Explain',
                'verbose_name_plural': 'Explains',
                'db_table': 'guides_explain',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExplainRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(default=0, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('reviewed', 'Ditinjau'), ('published', 'Terbit'), ('returned', 'Dikembalikan'), ('rejected', 'Ditolak'), ('draft', 'Konsep'), ('archive', 'Arsip')], default='draft', max_length=100)),
                ('changelog', models.TextField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Explain Revision',
                'verbose_name_plural': 'Explain Revisions',
                'db_table': 'guides_explain_revision',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sectionrevision',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sectionrevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sectionrevision',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Explain Content', 'verbose_name_plural': 'Explain Contents'},
        ),
        migrations.AlterModelTable(
            name='content',
            table='guides_explain_content',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionRevision',
        ),
        migrations.AddField(
            model_name='explainrevision',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explain_revisions', to='beacon.Content'),
        ),
        migrations.AddField(
            model_name='explainrevision',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explain_revisions', to='person.Person'),
        ),
        migrations.AddField(
            model_name='explainrevision',
            name='explain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explain_revisions', to='beacon.Explain'),
        ),
    ]
