# Generated by Django 2.2.9 on 2020-01-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0012_auto_20200111_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterrevision',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guiderevision',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
