# Generated by Django 2.2.9 on 2020-01-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0014_auto_20200115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explain',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explains', to='beacon.Guide'),
        ),
        migrations.AlterModelTable(
            name='content',
            table='guides_content',
        ),
    ]
