# Generated by Django 2.2.9 on 2020-01-26 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('beacon', '0015_auto_20200115_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255, null=True)),
                ('stage', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='person.Person')),
            ],
            options={
                'verbose_name': 'Sheet',
                'verbose_name_plural': 'Sheets',
                'db_table': 'guides_sheet',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-date_created'], 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='beacon.Category'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='person.Person'),
        ),
        migrations.CreateModel(
            name='SheetRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(default=0, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('reviewed', 'Ditinjau'), ('published', 'Terbit'), ('returned', 'Dikembalikan'), ('rejected', 'Ditolak'), ('draft', 'Konsep'), ('archive', 'Arsip')], default='draft', max_length=100)),
                ('changelog', models.TextField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_revisions', to='beacon.Content')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_revisions', to='person.Person')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_revisions', to='beacon.Sheet')),
            ],
            options={
                'verbose_name': 'Sheet Revision',
                'verbose_name_plural': 'Sheet Revisions',
                'db_table': 'guides_sheet_revision',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='beacon.Guide'),
        ),
    ]
