# Generated by Django 2.2.9 on 2020-02-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0018_auto_20200129_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Publik')], default='public', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explain',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Publik')], default='public', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Publik')], default='public', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privat'), ('public', 'Publik')], default='public', max_length=255, null=True),
        ),
    ]
