# Generated by Django 2.2.9 on 2020-02-08 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('person', '0002_person_is_validated'),
        ('beacon', '0020_auto_20200207_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='content_blob',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_blob',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='reply',
            table='beacon_discuss_reply',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='beacon_discuss_topic',
        ),
        migrations.CreateModel(
            name='TopicRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(default=0, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('content_blob', models.BinaryField()),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('reviewed', 'Ditinjau'), ('published', 'Terbit'), ('returned', 'Dikembalikan'), ('rejected', 'Ditolak'), ('draft', 'Konsep'), ('archive', 'Arsip')], default='draft', max_length=100)),
                ('changelog', models.TextField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(app_label='beacon'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_revisions', to='person.Person')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_revisions', to='beacon.Topic')),
            ],
            options={
                'verbose_name': 'Topic Revision',
                'verbose_name_plural': 'Topic Revisions',
                'db_table': 'beacon_discuss_topic_revision',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplyRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(default=0, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('content_blob', models.BinaryField()),
                ('status', models.CharField(choices=[('pending', 'Tertunda'), ('reviewed', 'Ditinjau'), ('published', 'Terbit'), ('returned', 'Dikembalikan'), ('rejected', 'Ditolak'), ('draft', 'Konsep'), ('archive', 'Arsip')], default='draft', max_length=100)),
                ('changelog', models.TextField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(app_label='beacon'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_revisions', to='person.Person')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_revisions', to='beacon.Reply')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_revisions', to='beacon.Topic')),
            ],
            options={
                'verbose_name': 'Reply Revision',
                'verbose_name_plural': 'Reply Revisions',
                'db_table': 'beacon_discuss_reply_revision',
                'abstract': False,
            },
        ),
    ]
