# Generated by Django 2.2.9 on 2020-02-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0021_auto_20200208_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replyrevision',
            options={'verbose_name': 'Discussion Reply Revision', 'verbose_name_plural': 'Discussion Reply Revisions'},
        ),
        migrations.AlterModelOptions(
            name='topicrevision',
            options={'verbose_name': 'Discussion Topic Revision', 'verbose_name_plural': 'Discussion Topic Revisions'},
        ),
        migrations.AlterField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='beacon.Reply'),
        ),
    ]
