# Generated by Django 2.2.9 on 2020-02-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0022_auto_20200208_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentchapter',
            options={'verbose_name': 'Enrollment Chapter', 'verbose_name_plural': 'Enrollment Chapters'},
        ),
        migrations.AlterModelOptions(
            name='enrollmentexplain',
            options={'verbose_name': 'Enrollment Explain', 'verbose_name_plural': 'Enrollment Explains'},
        ),
        migrations.AlterModelOptions(
            name='enrollmentguide',
            options={'verbose_name': 'Enrollment Guide', 'verbose_name_plural': 'Enrollment Guides'},
        ),
        migrations.RenameField(
            model_name='enrollmentchapter',
            old_name='enrollment',
            new_name='enrollment_guide',
        ),
        migrations.RenameField(
            model_name='enrollmentexplain',
            old_name='enrollment',
            new_name='enrollment_guide',
        ),
    ]
